### ISSUE TITLE
CSV should auto-update

### ISSUE THREAD

**Issue by vdavez** [ajschumacher/dc_mayor_schedule#1]
The original site dynamically adds the current date to the page (e.g., from the January 8, 2014, page, it would say Wednesday, January 29, 2014) even though the content is from the original date.

**Comment by ajschumacher** [comment]
Hi! I'm not sure what you mean; if I look at the [pull from January 8, 2014](https://github.com/ajschumacher/dc_mayor_schedule/blob/master/html/2014-01-08.html) I see only the date for that day, e.g., `content="2014-01-08T19:30:00-05:00"`. How can I see what you're seeing? Thanks!

**Comment by vdavez** [comment]
Here's the problematic line in the code: '

> var dayNames = new Array("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"); var monthNames = new Array("January","February","March","April","May","June","July","August","September","October","November","December"); var now = new Date(); document.write(dayNames[now.getDay()] + ", " + monthNames[now.getMonth()] + " " + now.getDate() + ", " + now.getFullYear());

**Comment by ajschumacher** [comment]
Hmm... Where is that code coming from?

**Comment by vdavez** [comment]
It's in the HTML on the site. Check line 304.

**Comment by ajschumacher** [comment]
Ah, yes, thanks! Does that affect anything though? For data extraction purposes, there are the "hard-coded" dates in the HTML for each event (like `content="2014-01-08T19:30:00-05:00"`, etc.). Does that work?

**Comment by vdavez** [comment]
Yes, but try saving the page to file and opening it in a browser. It shows up with today's date (which is how I discovered the code in the first place).

**Comment by ajschumacher** [comment]
You are correct; the correct date is embedded in the HTML still though, and it's in the archived file names, and it should come out correctly when [extracted](https://github.com/ajschumacher/dc_mayor_schedule/blob/master/code/html_to_tabular.py). Is there anything to do in order to resolve this issue in how it displays in a browser?

**Comment by vdavez** [comment]
Maybe we just chalk it up to an annoying quirk. Maybe another solution would be to have your crontab run the py script when updating github, so that the CSV is current. Then the browser is irrelevant. (i don't have python at work, otherwise I'd just run it myself)...

**Comment by ajschumacher** [comment]
That's a good point; keeping the CSV up to date was part of the original intent I think, but I never got it to the point that I felt comfortable just letting it run. I'll consider that the state to reach before closing this issue then. Thanks!

**Comment by ajschumacher** [comment]
Okay! I messed around a bunch and I think it might be working now! I'll check again tomorrow to confirm, but if all went as I think it did then it'll build the CSV every time it gets a new HTML file!

**Comment by ajschumacher** [comment]
Yes! It's working! Thanks again for motivating this, @vzvenyach!
