### ISSUE TITLE
Create a gh-pages branch for a web interface

### ISSUE THREAD

**Issue by shiftyp** [ajschumacher/dc_mayor_schedule#2]
I've created a gh-pages branch in my repository with a simple [web interface](http://shiftyp.github.io/dc_mayor_schedule/) displaying the mayor's schedule and allowing users to filter by date.  If you'd like me to create a pull request to merge this new branch into the project, you'll need to create an orphan gh-pages branch for me to create the pull request to.  Just follow the instructions [here](https://help.github.com/articles/creating-project-pages-manually), but instead of creating an index.html file, create a new README.md file with a description of the site.  This will allow you to push the branch, and allow a clean merge when I do the pull request.  You'll also need to update your cron-job to update the gh-pages branch if you want the page to stay up to date.

**Comment by shiftyp** [comment]
Oh, and if you look you'll see that there are some data quality issues that need to be worked out for the site to function optimally.

**Comment by ajschumacher** [comment]
Thanks! This looks so cool!

**Comment by ajschumacher** [comment]
The data quality issues you mentioned - do you mean for the addresses to get linked properly, or something else?

**Comment by shiftyp** [comment]
It looks like because our gh-pages branches have completely separate histories, github won't let me do a pull request.  I'll have to merge the branches manually and push to your gh-pages branch.  In order for that to work you'll have to add me as a collaborator on the repo.

The data quality issues have to do with newlines inside fields (the comments field is the culprit here), and the fact that some of the fields are quoted with internal special characters and some aren't.  I sort of figured out how to handle the newlines in the comments field, but I'm not sure if it is fixing all the records.  The special characters in quoted fields could probably be fixed on the frontend as well, I just didn't get to implementing a good solution.

The addresses thing is kind of tricky since I'm really just assuming that there is a consistent format for addresses, and it doesn't always hold true.  It sort of works though, so it's not a bad feature to have.

**Comment by ajschumacher** [comment]
Works for me! I just added you as a collaborator. I'll have to look at the data issues a little bit more...

**Comment by shiftyp** [comment]
Cool.  The page is now up at http://ajschumacher.github.io/dc_mayor_schedule/.  Like I said, we can probably handle the data issues on the frontend with a regexp, I just didn't get to it...I basically did this today in 3 hours and some change. ;)  If you'd like to take a stab at styling the page that would be great.  Right now its just using the default bootstrap styling.

**Comment by ajschumacher** [comment]
Excellent! If I can, I'll get the nightly job on the gh-pages branch and maybe take a look at the issues you mentioned before the next update tonight. What are you doing Monday? If you're free you should come to Hack and Tell and show what you did! http://www.meetup.com/DC-Hack-and-Tell/events/186068112/

**Comment by shiftyp** [comment]
Man, it doesn't show me as a contributor since I haven't pushed to master.  If you don't mind, I'll add a link to the github page on the readme in master; both to link to the page and to add myself as a contributor in github's eyes. ;)

**Comment by shiftyp** [comment]
I'll see if I can come on Monday, if not feel free to show off the new page in my place. :smile:

**Comment by ajschumacher** [comment]
haha sounds good! Thanks again for putting together the cool interface!

**Comment by shiftyp** [comment]
No problem!  Like I said some additional styling would be nice.  Feel free to take a stab at it, or I'll do it when I have some more free time.
