### ISSUE TITLE
Issue with multiple commas in a single quoted field

### ISSUE THREAD

**Issue by shiftyp** [ajschumacher/dc_mayor_schedule#4]
I've fixed most of the issues with parsing the CSV, but there is still an issue where there are [multiple commas in a quoted field](http://ajschumacher.github.io/dc_mayor_schedule/#/date/05-20-2014).  I'm not sure how to handle this with a regex on the frontend.

**Comment by ajschumacher** [comment]
Hmm what do you think about using something like jquery-csv instead of regex for the csv parsing?

**Comment by shiftyp** [comment]
Yeah, I was thinking of caving and using a library.  Let smarter people handle the regexes. :wink:

**Comment by shiftyp** [comment]
I ended up integrating jquery-csv as per your suggestion.  Seems to have fixed the issue.

**Comment by ajschumacher** [comment]
Nice! :+1:
