### ISSUE TITLE
web view fails on my iPhone :(

### ISSUE THREAD

**Issue by ajschumacher** [ajschumacher/dc_mayor_schedule#6]

**Comment by shiftyp** [comment]
What's the failure?

**Comment by ajschumacher** [comment]
It says there isn't anything found, for every date.

**Comment by shiftyp** [comment]
I'll check it out in the ios emulator and see what I can find out.

**Comment by shiftyp** [comment]
This should be fixed.  The issue on iPhone Safari (and possibly Safari too) had to do with the built in date parser failing to read dates in the format MM-DD-YYYY, which I used in the url.  Without a valid date, all data was filtered out for every selected day.  Setting an explicit format in the call to moment fixed the issue.

**Comment by ajschumacher** [comment]
Awesome - confirm fixes original issue. Thanks @shiftyp!

**Comment by ajschumacher** [comment]
Any reason not to close? Going for it...
